spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
      - id: api-1
        uri: lb://QUESTIONSERVICE
        predicates:
        - Path=/question
      - id: api-2
        uri: lb:// QUIZZSERVICE
        predicates:
        - Path=/quizz
server:
  port: 3030
